//@version=5
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © pranjalchaubey

//Structural Pivots
indicator(title='[CP]Pivot Boss Multi Timeframe CPR with MACD', shorttitle='[CP]Pivot Boss CPR + MACD', overlay=true, max_labels_count=500)


// User Inputs 
//==============================================================================
show_yearly_cpr             = input.bool(true,                          title='Yearly Pivot',       inline='yearly',    group='Multi Timeframe Central Pivot Range')
yearly_pivot_color          = input.color(color.new(color.yellow, 0),   title='',                   inline='yearly',    group='Multi Timeframe Central Pivot Range')
show_yearly_cpr_band        = input.bool(true,                          title='CPR Band',           inline='yearly',    group='Multi Timeframe Central Pivot Range')
yearly_cpr_color            = input.color(color.new(color.blue, 50),    title='',                   inline='yearly',    group='Multi Timeframe Central Pivot Range')

show_quarterly_cpr          = input.bool(true,                          title='Quarterly Pivot',    inline='quarterly', group='Multi Timeframe Central Pivot Range')
quarterly_pivot_color       = input.color(color.new(color.fuchsia, 0),  title='',                   inline='quarterly', group='Multi Timeframe Central Pivot Range')
show_quarterly_cpr_band     = input.bool(true,                          title='CPR Band',           inline='quarterly', group='Multi Timeframe Central Pivot Range')
quarterly_cpr_color         = input.color(color.new(color.olive, 50),   title='',                   inline='quarterly', group='Multi Timeframe Central Pivot Range')

show_monthly_cpr            = input.bool(false,                         title='Monthly Pivot',      inline='monthly',   group='Multi Timeframe Central Pivot Range')
monthly_pivot_color         = input.color(color.new(color.teal, 0),     title='',                   inline='monthly',   group='Multi Timeframe Central Pivot Range')
show_monthly_cpr_band       = input.bool(false,                         title='CPR Band',           inline='monthly',   group='Multi Timeframe Central Pivot Range')
monthly_cpr_color           = input.color(color.new(color.navy, 50),    title='',                   inline='monthly',   group='Multi Timeframe Central Pivot Range')

show_weekly_cpr             = input.bool(true,                          title='Weekly Pivot',       inline='weekly',    group='Multi Timeframe Central Pivot Range')
weekly_pivot_color          = input.color(color.new(color.orange, 0),   title='',                   inline='weekly',    group='Multi Timeframe Central Pivot Range')
show_weekly_cpr_band        = input.bool(true,                          title='CPR Band',           inline='weekly',    group='Multi Timeframe Central Pivot Range')
weekly_cpr_color            = input.color(color.new(color.purple, 50),  title='',                   inline='weekly',    group='Multi Timeframe Central Pivot Range')

show_daily_cpr              = input.bool(false,                         title='Daily Pivot',        inline='daily',     group='Multi Timeframe Central Pivot Range')
daily_pivot_color           = input.color(color.new(color.red, 0),      title='',                   inline='daily',     group='Multi Timeframe Central Pivot Range')
show_daily_cpr_band         = input.bool(false,                         title='CPR Band',           inline='daily',     group='Multi Timeframe Central Pivot Range')
daily_cpr_color             = input.color(color.new(color.lime, 50),    title='',                   inline='daily',     group='Multi Timeframe Central Pivot Range')

show_hourly_cpr             = input.bool(false,                         title='Hourly Pivot',       inline='hourly',    group='Multi Timeframe Central Pivot Range')
hourly_pivot_color          = input.color(color.new(color.green, 0),    title='',                   inline='hourly',    group='Multi Timeframe Central Pivot Range')
show_hourly_cpr_band        = input.bool(false,                         title='CPR Band',           inline='hourly',    group='Multi Timeframe Central Pivot Range')
hourly_cpr_color            = input.color(color.new(color.gray, 50),    title='',                   inline='hourly',    group='Multi Timeframe Central Pivot Range')


show_labels                 = input.bool(true,                          title='Show CPR Lables',                        group='Multi Timeframe Central Pivot Range')
show_next_day_pivot         = input.bool(false,                         title='Show Next Time Period Pivots',           group='Multi Timeframe Central Pivot Range')






// Calculations  
//==============================================================================
// Floor Pivots 
// Central Pivot 
pivot = (high + low + close) / 3.0
// Central Pivot Range 
temp_bc = (high + low) / 2
temp_tc = pivot - temp_bc + pivot
tc = temp_tc > temp_bc ? temp_tc : temp_bc
bc = temp_bc < temp_tc ? temp_bc : temp_tc


// Multi Timeframe CPR 
//==============================================================================
yearly_pivot        = request.security(syminfo.tickerid, '12M', show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
yearly_tbc          = request.security(syminfo.tickerid, '12M', show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
yearly_ttc          = request.security(syminfo.tickerid, '12M', show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
yearly_tc           = yearly_ttc > yearly_tbc ? yearly_ttc : yearly_tbc
yearly_bc           = yearly_tbc < yearly_ttc ? yearly_tbc : yearly_ttc
quarterly_pivot     = request.security(syminfo.tickerid, '3M',  show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
quarterly_tbc       = request.security(syminfo.tickerid, '3M',  show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
quarterly_ttc       = request.security(syminfo.tickerid, '3M',  show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
quarterly_tc        = quarterly_ttc > quarterly_tbc ? quarterly_ttc : quarterly_tbc
quarterly_bc        = quarterly_tbc < quarterly_ttc ? quarterly_tbc : quarterly_ttc
monthly_pivot       = request.security(syminfo.tickerid, 'M',   show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
monthly_tbc         = request.security(syminfo.tickerid, 'M',   show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
monthly_ttc         = request.security(syminfo.tickerid, 'M',   show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
monthly_tc          = monthly_ttc > monthly_tbc ? monthly_ttc : monthly_tbc
monthly_bc          = monthly_tbc < monthly_ttc ? monthly_tbc : monthly_ttc
weekly_pivot        = request.security(syminfo.tickerid, 'W',   show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
weekly_tbc          = request.security(syminfo.tickerid, 'W',   show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
weekly_ttc          = request.security(syminfo.tickerid, 'W',   show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
weekly_tc           = weekly_ttc > weekly_tbc ? weekly_ttc : weekly_tbc
weekly_bc           = weekly_tbc < weekly_ttc ? weekly_tbc : weekly_ttc
daily_pivot         = request.security(syminfo.tickerid, 'D',   show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
daily_tbc           = request.security(syminfo.tickerid, 'D',   show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
daily_ttc           = request.security(syminfo.tickerid, 'D',   show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
daily_tc            = daily_ttc > daily_tbc ? daily_ttc : daily_tbc
daily_bc            = daily_tbc < daily_ttc ? daily_tbc : daily_ttc
hourly_pivot        = request.security(syminfo.tickerid, '60',  show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
hourly_tbc          = request.security(syminfo.tickerid, '60',  show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
hourly_ttc          = request.security(syminfo.tickerid, '60',  show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
hourly_tc           = hourly_ttc > hourly_tbc ? hourly_ttc : hourly_tbc
hourly_bc           = hourly_tbc < hourly_ttc ? hourly_tbc : hourly_ttc


// Plots   
//==============================================================================
// Yearly CPR   
yearly_pivot_plot       = plot(show_yearly_cpr          ? yearly_pivot      : na, title='Yearly Pivot',     color=color.new(yearly_pivot_color, 0),     linewidth=1, style=plot.style_circles)
yearly_tcline           = plot(show_yearly_cpr_band     ? yearly_tc         : na, title='Yearly TC',        color=color.new(yearly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
yearly_bcline           = plot(show_yearly_cpr_band     ? yearly_bc         : na, title='Yearly BC',        color=color.new(yearly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
fill(yearly_tcline, yearly_bcline, color=color.new(yearly_cpr_color, show_yearly_cpr_band ? 95 : 100))
// Quarterly CPR   
quarterly_pivot_plot    = plot(show_quarterly_cpr       ? quarterly_pivot   : na, title='Quarterly Pivot',  color=color.new(quarterly_pivot_color, 0),  linewidth=1, style=plot.style_circles)
quarterly_tcline        = plot(show_quarterly_cpr_band  ? quarterly_tc      : na, title='Quarterly TC',     color=color.new(quarterly_cpr_color, 0),    linewidth=0, style=plot.style_circles)
quarterly_bcline        = plot(show_quarterly_cpr_band  ? quarterly_bc      : na, title='Quarterly BC',     color=color.new(quarterly_cpr_color, 0),    linewidth=0, style=plot.style_circles)
fill(quarterly_tcline, quarterly_bcline, color=color.new(quarterly_cpr_color, show_quarterly_cpr_band ? 95 : 100))
// Monthly CPR   
monthly_pivot_plot      = plot(show_monthly_cpr         ? monthly_pivot     : na, title='Monthly Pivot',    color=color.new(monthly_pivot_color, 0),    linewidth=1, style=plot.style_circles)
monthly_tcline          = plot(show_monthly_cpr_band    ? monthly_tc        : na, title='Monthly TC',       color=color.new(monthly_cpr_color, 0),      linewidth=0, style=plot.style_circles)
monthly_bcline          = plot(show_monthly_cpr_band    ? monthly_bc        : na, title='Monthly BC',       color=color.new(monthly_cpr_color, 0),      linewidth=0, style=plot.style_circles)
fill(monthly_tcline, monthly_bcline, color=color.new(monthly_cpr_color, show_monthly_cpr_band ? 95 : 100))
// Weekly CPR   
weekly_pivot_plot       = plot(show_weekly_cpr          ? weekly_pivot      : na, title='Weekly Pivot',     color=color.new(weekly_pivot_color, 0),     linewidth=1, style=plot.style_circles)
weekly_tcline           = plot(show_weekly_cpr_band     ? weekly_tc         : na, title='Weekly TC',        color=color.new(weekly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
weekly_bcline           = plot(show_weekly_cpr_band     ? weekly_bc         : na, title='Weekly BC',        color=color.new(weekly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
fill(weekly_tcline, weekly_bcline, color=color.new(weekly_cpr_color, show_weekly_cpr_band ? 95 : 100))
// Daily CPR   
daily_pivot_plot        = plot(show_daily_cpr           ? daily_pivot       : na, title='Daily Pivot',      color=color.new(daily_pivot_color, 0),      linewidth=1, style=plot.style_circles)
daily_tcline            = plot(show_daily_cpr_band      ? daily_tc          : na, title='Daily TC',         color=color.new(daily_cpr_color, 0),        linewidth=0, style=plot.style_circles)
daily_bcline            = plot(show_daily_cpr_band      ? daily_bc          : na, title='Daily BC',         color=color.new(daily_cpr_color, 0),        linewidth=0, style=plot.style_circles)
fill(daily_tcline, daily_bcline, color=color.new(daily_cpr_color, show_daily_cpr_band ? 95 : 100))
// Hourly CPR   
hourly_pivot_plot       = plot(show_hourly_cpr          ? hourly_pivot      : na, title='Hourly Pivot',     color=color.new(hourly_pivot_color, 0),     linewidth=1, style=plot.style_circles)
hourly_tcline           = plot(show_hourly_cpr_band     ? hourly_tc         : na, title='Hourly TC',        color=color.new(hourly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
hourly_bcline           = plot(show_hourly_cpr_band     ? hourly_bc         : na, title='Hourly BC',        color=color.new(hourly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
fill(hourly_tcline, hourly_bcline, color=color.new(hourly_cpr_color, show_hourly_cpr_band ? 95 : 100))


// CPR Labels  
if show_labels
    chper = time - time[1]
    chper := ta.change(chper) > 0 ? chper[1] : chper

    var label yearly_pivot_label        = na   
    var label quarterly_pivot_label     = na   
    var label monthly_pivot_label       = na   
    var label weekly_pivot_label        = na   
    var label daily_pivot_label         = na   
    var label hourly_pivot_label        = na   

    label.delete(yearly_pivot_label)
    label.delete(quarterly_pivot_label)
    label.delete(monthly_pivot_label)
    label.delete(weekly_pivot_label)
    label.delete(daily_pivot_label)
    label.delete(hourly_pivot_label)
    if show_yearly_cpr
        yearly_pivot_label      := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = yearly_pivot,     text = "Yearly Pivot",      color = yearly_pivot_color,     textcolor=color.black, style=label.style_label_down, xloc = xloc.bar_time, yloc=yloc.price) 
    if show_quarterly_cpr
        quarterly_pivot_label   := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = quarterly_pivot,  text = "Quarterly Pivot",   color = quarterly_pivot_color,  textcolor=color.black, style=label.style_label_down, xloc = xloc.bar_time, yloc=yloc.price) 
    if show_monthly_cpr
        monthly_pivot_label     := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = monthly_pivot,    text = "Monthly Pivot",     color = monthly_pivot_color,    textcolor=color.black, style=label.style_label_down, xloc = xloc.bar_time, yloc=yloc.price) 
    if show_weekly_cpr
        weekly_pivot_label      := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = weekly_pivot,     text = "Weekly Pivot",      color = weekly_pivot_color,     textcolor=color.black, style=label.style_label_down, xloc = xloc.bar_time, yloc=yloc.price) 
    if show_daily_cpr
        daily_pivot_label       := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = daily_pivot,      text = "Daily Pivot",       color = daily_pivot_color,      textcolor=color.black, style=label.style_label_down, xloc = xloc.bar_time, yloc=yloc.price) 
    if show_hourly_cpr
        hourly_pivot_label      := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = hourly_pivot,     text = "Hourly Pivot",      color = hourly_pivot_color,     textcolor=color.black, style=label.style_label_down, xloc = xloc.bar_time, yloc=yloc.price) 
