//@version=5
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © pranjalchaubey

//Structural Pivots
indicator(title='[CP]Pivot Boss Multi Timeframe CPR with MACD', shorttitle='[CP]Pivot Boss CPR + MACD', overlay=true, max_labels_count=500)


// User Inputs 
//==============================================================================
show_yearly_cpr             = input.bool(true,                          title='Yearly Pivot',       inline='yearly',    group='Multi Timeframe Central Pivot Range')
yearly_pivot_color          = input.color(color.new(color.yellow, 0),   title='',                   inline='yearly',    group='Multi Timeframe Central Pivot Range')
show_yearly_cpr_band        = input.bool(true,                          title='CPR Band',           inline='yearly',    group='Multi Timeframe Central Pivot Range')
yearly_cpr_color            = input.color(color.new(color.blue, 50),    title='',                   inline='yearly',    group='Multi Timeframe Central Pivot Range')

show_quarterly_cpr          = input.bool(true,                          title='Quarterly Pivot',    inline='quarterly', group='Multi Timeframe Central Pivot Range')
quarterly_pivot_color       = input.color(color.new(color.fuchsia, 0),  title='',                   inline='quarterly', group='Multi Timeframe Central Pivot Range')
show_quarterly_cpr_band     = input.bool(true,                          title='CPR Band',           inline='quarterly', group='Multi Timeframe Central Pivot Range')
quarterly_cpr_color         = input.color(color.new(color.olive, 50),   title='',                   inline='quarterly', group='Multi Timeframe Central Pivot Range')

show_monthly_cpr            = input.bool(false,                         title='Monthly Pivot',      inline='monthly',   group='Multi Timeframe Central Pivot Range')
monthly_pivot_color         = input.color(color.new(color.teal, 0),     title='',                   inline='monthly',   group='Multi Timeframe Central Pivot Range')
show_monthly_cpr_band       = input.bool(false,                         title='CPR Band',           inline='monthly',   group='Multi Timeframe Central Pivot Range')
monthly_cpr_color           = input.color(color.new(color.navy, 50),    title='',                   inline='monthly',   group='Multi Timeframe Central Pivot Range')

show_weekly_cpr             = input.bool(true,                          title='Weekly Pivot',       inline='weekly',    group='Multi Timeframe Central Pivot Range')
weekly_pivot_color          = input.color(color.new(color.orange, 0),   title='',                   inline='weekly',    group='Multi Timeframe Central Pivot Range')
show_weekly_cpr_band        = input.bool(true,                          title='CPR Band',           inline='weekly',    group='Multi Timeframe Central Pivot Range')
weekly_cpr_color            = input.color(color.new(color.purple, 50),  title='',                   inline='weekly',    group='Multi Timeframe Central Pivot Range')

show_daily_cpr              = input.bool(false,                         title='Daily Pivot',        inline='daily',     group='Multi Timeframe Central Pivot Range')
daily_pivot_color           = input.color(color.new(color.red, 0),      title='',                   inline='daily',     group='Multi Timeframe Central Pivot Range')
show_daily_cpr_band         = input.bool(false,                         title='CPR Band',           inline='daily',     group='Multi Timeframe Central Pivot Range')
daily_cpr_color             = input.color(color.new(color.lime, 50),    title='',                   inline='daily',     group='Multi Timeframe Central Pivot Range')

show_hourly_cpr             = input.bool(false,                         title='Hourly Pivot',       inline='hourly',    group='Multi Timeframe Central Pivot Range')
hourly_pivot_color          = input.color(color.new(color.green, 0),    title='',                   inline='hourly',    group='Multi Timeframe Central Pivot Range')
show_hourly_cpr_band        = input.bool(false,                         title='CPR Band',           inline='hourly',    group='Multi Timeframe Central Pivot Range')
hourly_cpr_color            = input.color(color.new(color.gray, 50),    title='',                   inline='hourly',    group='Multi Timeframe Central Pivot Range')


show_labels                 = input.bool(true,                          title='Show CPR Lables',                        group='Multi Timeframe Central Pivot Range')
show_next_day_pivot         = input.bool(false,                         title='Show Next Time Period Pivots',           group='Multi Timeframe Central Pivot Range')






// Calculations  
//==============================================================================
// Floor Pivots 
// Central Pivot 
pivot = (high + low + close) / 3.0
// Central Pivot Range 
temp_bc = (high + low) / 2
temp_tc = pivot - temp_bc + pivot
tc = temp_tc > temp_bc ? temp_tc : temp_bc
bc = temp_bc < temp_tc ? temp_bc : temp_tc


// Multi Timeframe CPR 
//==============================================================================
yearly_pivot        = request.security(syminfo.tickerid, '12M', show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
yearly_tbc          = request.security(syminfo.tickerid, '12M', show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
yearly_ttc          = request.security(syminfo.tickerid, '12M', show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
yearly_tc           = yearly_ttc > yearly_tbc ? yearly_ttc : yearly_tbc
yearly_bc           = yearly_tbc < yearly_ttc ? yearly_tbc : yearly_ttc
quarterly_pivot     = request.security(syminfo.tickerid, '3M',  show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
quarterly_tbc       = request.security(syminfo.tickerid, '3M',  show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
quarterly_ttc       = request.security(syminfo.tickerid, '3M',  show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
quarterly_tc        = quarterly_ttc > quarterly_tbc ? quarterly_ttc : quarterly_tbc
quarterly_bc        = quarterly_tbc < quarterly_ttc ? quarterly_tbc : quarterly_ttc
monthly_pivot       = request.security(syminfo.tickerid, 'M',   show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
monthly_tbc         = request.security(syminfo.tickerid, 'M',   show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
monthly_ttc         = request.security(syminfo.tickerid, 'M',   show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
monthly_tc          = monthly_ttc > monthly_tbc ? monthly_ttc : monthly_tbc
monthly_bc          = monthly_tbc < monthly_ttc ? monthly_tbc : monthly_ttc
weekly_pivot        = request.security(syminfo.tickerid, 'W',   show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
weekly_tbc          = request.security(syminfo.tickerid, 'W',   show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
weekly_ttc          = request.security(syminfo.tickerid, 'W',   show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
weekly_tc           = weekly_ttc > weekly_tbc ? weekly_ttc : weekly_tbc
weekly_bc           = weekly_tbc < weekly_ttc ? weekly_tbc : weekly_ttc
daily_pivot         = request.security(syminfo.tickerid, 'D',   show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
daily_tbc           = request.security(syminfo.tickerid, 'D',   show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
daily_ttc           = request.security(syminfo.tickerid, 'D',   show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
daily_tc            = daily_ttc > daily_tbc ? daily_ttc : daily_tbc
daily_bc            = daily_tbc < daily_ttc ? daily_tbc : daily_ttc
hourly_pivot        = request.security(syminfo.tickerid, '60',  show_next_day_pivot ? pivot     : pivot[1],     barmerge.gaps_off, barmerge.lookahead_on)
hourly_tbc          = request.security(syminfo.tickerid, '60',  show_next_day_pivot ? temp_bc   : temp_bc[1],   barmerge.gaps_off, barmerge.lookahead_on)
hourly_ttc          = request.security(syminfo.tickerid, '60',  show_next_day_pivot ? temp_tc   : temp_tc[1],   barmerge.gaps_off, barmerge.lookahead_on)
hourly_tc           = hourly_ttc > hourly_tbc ? hourly_ttc : hourly_tbc
hourly_bc           = hourly_tbc < hourly_ttc ? hourly_tbc : hourly_ttc


// Plots   
//==============================================================================
// Yearly CPR   
yearly_pivot_plot       = plot(show_yearly_cpr          ? yearly_pivot      : na, title='Yearly Pivot',     color=color.new(yearly_pivot_color, 0),     linewidth=1, style=plot.style_circles)
yearly_tcline           = plot(show_yearly_cpr_band     ? yearly_tc         : na, title='Yearly TC',        color=color.new(yearly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
yearly_bcline           = plot(show_yearly_cpr_band     ? yearly_bc         : na, title='Yearly BC',        color=color.new(yearly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
fill(yearly_tcline, yearly_bcline, color=color.new(yearly_cpr_color, show_yearly_cpr_band ? 95 : 100))
// Quarterly CPR   
quarterly_pivot_plot    = plot(show_quarterly_cpr       ? quarterly_pivot   : na, title='Quarterly Pivot',  color=color.new(quarterly_pivot_color, 0),  linewidth=1, style=plot.style_circles)
quarterly_tcline        = plot(show_quarterly_cpr_band  ? quarterly_tc      : na, title='Quarterly TC',     color=color.new(quarterly_cpr_color, 0),    linewidth=0, style=plot.style_circles)
quarterly_bcline        = plot(show_quarterly_cpr_band  ? quarterly_bc      : na, title='Quarterly BC',     color=color.new(quarterly_cpr_color, 0),    linewidth=0, style=plot.style_circles)
fill(quarterly_tcline, quarterly_bcline, color=color.new(quarterly_cpr_color, show_quarterly_cpr_band ? 95 : 100))
// Monthly CPR   
monthly_pivot_plot      = plot(show_monthly_cpr         ? monthly_pivot     : na, title='Monthly Pivot',    color=color.new(monthly_pivot_color, 0),    linewidth=1, style=plot.style_circles)
monthly_tcline          = plot(show_monthly_cpr_band    ? monthly_tc        : na, title='Monthly TC',       color=color.new(monthly_cpr_color, 0),      linewidth=0, style=plot.style_circles)
monthly_bcline          = plot(show_monthly_cpr_band    ? monthly_bc        : na, title='Monthly BC',       color=color.new(monthly_cpr_color, 0),      linewidth=0, style=plot.style_circles)
fill(monthly_tcline, monthly_bcline, color=color.new(monthly_cpr_color, show_monthly_cpr_band ? 95 : 100))
// Weekly CPR   
weekly_pivot_plot       = plot(show_weekly_cpr          ? weekly_pivot      : na, title='Weekly Pivot',     color=color.new(weekly_pivot_color, 0),     linewidth=1, style=plot.style_circles)
weekly_tcline           = plot(show_weekly_cpr_band     ? weekly_tc         : na, title='Weekly TC',        color=color.new(weekly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
weekly_bcline           = plot(show_weekly_cpr_band     ? weekly_bc         : na, title='Weekly BC',        color=color.new(weekly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
fill(weekly_tcline, weekly_bcline, color=color.new(weekly_cpr_color, show_weekly_cpr_band ? 95 : 100))
// Daily CPR   
daily_pivot_plot        = plot(show_daily_cpr           ? daily_pivot       : na, title='Daily Pivot',      color=color.new(daily_pivot_color, 0),      linewidth=1, style=plot.style_circles)
daily_tcline            = plot(show_daily_cpr_band      ? daily_tc          : na, title='Daily TC',         color=color.new(daily_cpr_color, 0),        linewidth=0, style=plot.style_circles)
daily_bcline            = plot(show_daily_cpr_band      ? daily_bc          : na, title='Daily BC',         color=color.new(daily_cpr_color, 0),        linewidth=0, style=plot.style_circles)
fill(daily_tcline, daily_bcline, color=color.new(daily_cpr_color, show_daily_cpr_band ? 95 : 100))
// Hourly CPR   
hourly_pivot_plot       = plot(show_hourly_cpr          ? hourly_pivot      : na, title='Hourly Pivot',     color=color.new(hourly_pivot_color, 0),     linewidth=1, style=plot.style_circles)
hourly_tcline           = plot(show_hourly_cpr_band     ? hourly_tc         : na, title='Hourly TC',        color=color.new(hourly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
hourly_bcline           = plot(show_hourly_cpr_band     ? hourly_bc         : na, title='Hourly BC',        color=color.new(hourly_cpr_color, 0),       linewidth=0, style=plot.style_circles)
fill(hourly_tcline, hourly_bcline, color=color.new(hourly_cpr_color, show_hourly_cpr_band ? 95 : 100))


// // CPR Labels  
// if show_labels
//     chper = time - time[1]
//     chper := change(chper) > 0 ? chper[1] : chper

//     var label yearly_pivot_label    = na,   yearly_tc_label     = na,   yearly_bc_label     = na 
//     var label quarterly_pivot_label = na,   quarterly_tc_label  = na,   quarterly_bc_label  = na 
//     var label monthly_pivot_label   = na,   monthly_tc_label    = na,   monthly_bc_label    = na 
//     var label weekly_pivot_label    = na,   weekly_tc_label     = na,   weekly_bc_label     = na 
//     var label daily_pivot_label     = na,   daily_tc_label      = na,   daily_bc_label      = na 
//     var label hourly_pivot_label    = na,   hourly_tc_label     = na,   hourly_bc_label     = na 

//     label.delete(yearly_pivot_label),       label.delete(yearly_tc_label),      label.delete(yearly_bc_label)
//     label.delete(quarterly_pivot_label),    label.delete(quarterly_tc_label),   label.delete(quarterly_bc_label)
//     label.delete(monthly_pivot_label),      label.delete(monthly_tc_label),     label.delete(monthly_bc_label)
//     label.delete(weekly_pivot_label),       label.delete(weekly_tc_label),      label.delete(weekly_bc_label)
//     label.delete(daily_pivot_label),        label.delete(daily_tc_label),       label.delete(daily_bc_label)
//     label.delete(hourly_pivot_label),       label.delete(hourly_tc_label),      label.delete(hourly_bc_label)
    // if show_yearly_cpr
    //     plabel  := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_pivot+daily_atr_dilation    : daily_pivot,  text = "Pivot", color = floor_pivots_p_color, textcolor=color.black, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price) 
    // if show_floor_pivots and show_daily_r1
    //     r1label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_r1+daily_atr_dilation       : daily_r1,     text = "R1",    color = floor_pivots_r_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_r2
    //     r2label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_r2+daily_atr_dilation       : daily_r2,     text = "R2",    color = floor_pivots_r_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_r3
    //     r3label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_r3+daily_atr_dilation       : daily_r3,     text = "R3",    color = floor_pivots_r_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_r4
    //     r4label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_r4+daily_atr_dilation       : daily_r4,     text = "R4",    color = floor_pivots_r_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_s1
    //     s1label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_s1+daily_atr_dilation       : daily_s1,     text = "S1",    color = floor_pivots_s_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_s2
    //     s2label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_s2+daily_atr_dilation       : daily_s2,     text = "S2",    color = floor_pivots_s_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_s3
    //     s3label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_s3+daily_atr_dilation       : daily_s3,     text = "S3",    color = floor_pivots_s_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
    // if show_floor_pivots and show_daily_s4
    //     s4label := label.new(x = timeframe.isintraday ? time + chper * 5 :  time + chper, y = atr_dilation and timeframe.isintraday ? daily_s4+daily_atr_dilation       : daily_s4,     text = "S4",    color = floor_pivots_s_color, textcolor=color.white, style=label.style_labeldown, xloc = xloc.bar_time, yloc=yloc.price)
